spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qima-db
    username: qima-user
    password: Password!!123
  
  # Flyway Configuration
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration
logging:
  level:
    org.springframework.jdbc.core: TRACE
    org.flywaydb: DEBUG
